import time
import config.config
from usecase.csv import write_csv

# web driver
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

# copy clipboard
import pyperclip 

class UberSuggest:

    def __init__(self):
        pass

    def sign_in(self):
        print('start uber suggest')

        # headless mode ヘッドレスモード
        options = Options()

        # running iPhoneX on an emulated screen. iPhoneXをエミュレートした画面で実行する
        # mobile_emulation = {'deviceName': 'iPhone X'}
        # options.add_experimental_option('mobileEmulation', mobile_emulation)

        # Chrome listening for debug communication on port 9222. ポート9222でデバッグ通信を待ち受けているChromeを操作する
        options.add_argument('--remote-debugging-port=9222')
        options.add_argument('--remote-debugging-address=127.0.0.1')

        # Specify where to save the profile. プロファイルの保存先を指定
        options.add_argument(
            '--user-data-dir=' + config.config.USER_DATA_DIR)
        # Specify the profile to use. 使用するプロファイルを指定
        options.add_argument('--profile-directory=Default')

        options.add_argument('--headless')
        driver = webdriver.Chrome(
            '../../driver/chromedriver',
            options=options
        )

        driver.implicitly_wait(5)

        driver.get(
            'https://app.neilpatel.com/ja/login')

        time.sleep(5)

        # sign in to uber suggest サインイン
        email_input = driver.find_element(By.NAME, 'email')
        email_input.clear()
        email_input.send_keys(config.config.UBER_SUGGEST_EMAIL)
        email_input.submit()

        time.sleep(5)

        password_input = driver.find_element(By.NAME, 'password')
        password_input.clear()
        password_input.send_keys(config.config.UBER_SUGGEST_PASSWORD)
        password_input.submit()

        button = driver.find_element(By.CSS_SELECTOR, '.sc-gSYCTC chVsAt')
        button.click()

        time.sleep(5)

        #  generate meta title　メタタイトルを生成
    def generate_meta_title(self, keyword):
        driver.get('https://app.neilpatel.com/ja/labs/ai_writer')

        time.sleep(5)

        first_button = driver.find_element(By.CSS_SELECTOR, '.sc-khIgXV')
        first_button.click()

        time.sleep(5)

        keyword_input = driver.find_element(By.CSS_SELECTOR, '.sc-bVDCDz')
        keyword_input.clear()
        keyword_input.send_keys(keyword)
        # keyword_input.submit()

        second_button = driver.find_element(By.CSS_SELECTOR, '.sc-eBnaGZ')
        second_button.click()

        time.sleep(5)

        copy_button = driver.find_element(By.CSS_SELECTOR, '#copyToolClipboard')
        copy_button.click()

        paste_str = pyperclip.paste()
        print("meta title generated by uber suggest",paste_str)
            

        #  generate meta description　メタディスクリプションを生成

        #  generate keywords　キーワードを生成

        #  generate content　コンテンツを生成

        #  generate paragraph　パラグラフを生成

        #  rewrite paragraph　パラグラフを書き換える

    #  sign out
    def sign_out(self):
        sign_out_button = driver.find_element(By.CSS_SELECTOR, '.sc-bnFUrP')
        sign_out_button.click()

    # quit driver
    def quit(self):
        driver.quit()
        print('quit uber suggest')